messageToTheWorld: Hello to you!

# Default server configuration for deployed environments
server:
  applicationConnectors:
  - type: http
    port: 8080
  adminConnectors:
  - type: http
    port: 8081
